### ISSUE TITLE
3.11 has released.

### ISSUE THREAD

**Issue by laozhou0731** [Websoft9/ansible-codeserver#5]
**What type of your feature request?**  

- [ ] Add new features
- [ ] Improve current features

**Is your feature request related to a problem? Please describe.**  

**Describe the solution you'd like**  

**Describe alternatives you've considered**  

**Additional context**

**Comment by geraintlyu** [comment]
# the version of codeserver is ok!
![codeserver](https://user-images.githubusercontent.com/53968450/126022922-093bb2d6-c4a2-4ed2-9f94-a18782c8c96f.png)
