### ISSUE TITLE
can not output the version number of "codeserver"

### ISSUE THREAD

**Issue by morning-tan** [Websoft9/ansible-codeserver#8]
**Describe the bug**

can not output the version number of "codeserver"
  
![image](https://user-images.githubusercontent.com/54173243/154916554-f7ecedad-10a2-43b5-8ea6-8311eace6635.png)

## Deployment method

- [ ] subscription image from MarketPlace of Cloud
- [ ] All-in-one Installer
- [ ] ansible-playbook cli
- [x] mcloud
- [ ] create instance from private image

## Bug source

- [ ] Bugs from installation 
- [ ] Bugs from first use
- [x] Other (You should describe it)   

## System Environment

**Application Version**

?

**OS**

- [ ] Ubuntu18.x
- [ ] Ubuntu20.x
- [x] CentOS7.x
- [ ] CentOS8.x
- [ ] AmazonLinux2
- [ ] OracleLinux7.8
- [ ] OracleLinux8.2
- [ ] Other (You should describe it) 

**Cloud PlatForm**

- [x] Azure
- [ ] Aws
- [ ] 阿里云
- [ ] 腾讯云
- [ ] 华为云
- [ ] AlibabaCloud
- [ ] HUWEICloud
- [ ] Other (You should describe it) 

### Bug Context

Bug context includes bug error, error logs and service status, it is very important for resolving issue

```
# bug error
(paste here) 

# service status 
(paste here) 

# error logs
(paste here) 
```

### Bug Screenshot

paste screenshot here

## Your suggestion

**The reason of Bug**

You can describe the reason if you have found it

**Your solution for Bug**

You can describe your solution here

**Additional context**

You can add any other context about the problem here.

**Comment by xiefei51** [comment]
在ansible项目中，没有找到输出版本的地方，但在 ansible-codeserver/vars/main.yml 文件中，发现codeserver是docker_applications的items之一，于是去找role_docker
在 role_docker/vars/main.yml 文件中，"codeserver"的check_version是查找版本的代码
在 role_docker/tasks/apps.yml 文件中，"Chcek {{docker_appname}} version"是调用check_version并输出版本的代码
bug原因：check_version的代码不对
修改为： docker inspect codeserver | grep org.opencontainers.image.version | cut -d: -f2
在docker-hub上查看镜像版本信息，确认输出的版本是正确的
已测试成功：
![image](https://user-images.githubusercontent.com/100544684/158496893-8f86b65c-3307-45f7-a44f-52e9abbef500.png)
